version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/main"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "/main"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
    target-branch: "develop"
