name: "Lint and Prettier"

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.16.0'
        cache: "npm"
        cache-dependency-path: "./main/package-lock.json"

    - name: Install dependencies
      run: npm ci
      working-directory: ./main

    - name: Run ESLint
      run: npx eslint --ext .js,.jsx,.ts,.tsx
      working-directory: ./main

    - name: Run Prettier
      run: npx prettier --check ./main
      working-directory: ./
