name: "Lint and Prettier"

on:
  pull_request_target:
    branches: [ "develop" ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: "20.16.0"
        cache: "npm"
        cache-dependency-path: "./main/package-lock.json"

    - name: Install dependencies
      run: npm ci
      working-directory: ./main

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44.5.7
      with:
        since_last_remote_commit: true
    
    - name: Run ESLint
      if: steps.changed-files.outputs.all_changed_files != ''
      run: |
        npx eslint --ext .ts,.tsx $(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -E '\.ts$|\.tsx$')
      working-directory: ./main
    
    - name: Run Prettier
      if: steps.changed-files.outputs.all_changed_files != ''
      run: |
        npx prettier --check $(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -E '\.ts$|\.tsx$')
      working-directory: ./main